version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/models
    volumes:
      - ./models:/models
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    dns:
      - 8.8.8.8
      - 1.1.1.1

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=False
    volumes:
      - openwebui_data:/app/backend/data
    restart: unless-stopped
    depends_on:
      - ollama

volumes:
  openwebui_data:
